- name: testing
  hosts: all
  # become: yes #for sudo
  tasks:
  - name: testing 
    ping:

  - name: install 
    become: yes 
    apt:
      name:
      - slapd
      - ldap-utils
      state: present
  
  - name: start service
    service:
      name: slapd
      state: started



# - name : openldap-installer
#   hosts: all
#   # become: yes #for sudo
#   tasks:
#   - name: installopenldap
#     become: yes
#     dnf: 
#       - slapd 
#       - ldap-utils
    
